"""RUCKUS constants."""

# API endpoints
API_VERSION = "v1"
AGENT_REGISTRATION_ENDPOINT = f"/api/{API_VERSION}/agents/register"
JOB_ENDPOINT = f"/api/{API_VERSION}/jobs"

# Default configuration
DEFAULT_SERVER_PORT = 8000
DEFAULT_AGENT_PORT = 8001
DEFAULT_POLL_INTERVAL = 30

# Timeouts
JOB_TIMEOUT_SECONDS = 3600
AGENT_HEARTBEAT_TIMEOUT = 300
