[project]
name = "ruckus-agent"
version = "0.1.0"
description = "RUCKUS distributed benchmarking agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pynvml",
    "torch",
    "numpy<2",
]
